### ISSUE TITLE
How to deal with database going down?

### ISSUE THREAD

**Issue by elie222** [elixir-mongo/mongodb#141]
If we the database is shut off, Elixir will crash after retrying 5 times in 5 seconds. How we have things at the moment is that it will bring down our entire application.

This may be alright for us. I'm not sure how much we can do when our database is down. Question is how do we stick things back up when this happens? What's the recommended way to check for restart a minute later to see if mongo connection is back?

**Comment by michalmuskala** [comment]
This sounds like there's some fault in the driver. `db_connection` itself is generally geared towards an incremental backoff to reconnect instead of crashing in case of failure. What processes exactly are crashing? I'm suspecting there might be something up with the new topology thingy since it's outside `db_connection` itself.

**Comment by ben-ic** [comment]
I was able to pinpoint where the problem is in the mongodb package.

In lib/mongo/protocol.ex not all possible disconnect reasons are taken into account
```ruby
defp connect(opts, s) do
    ...
    case result do
      {:ok, s} ->
        {:ok, s}
      {:disconnect, {:tcp_recv, reason}, _s} ->
        {:error, Mongo.Error.exception(tag: :tcp, action: "recv", reason: reason)}
      {:disconnect, {:tcp_send, reason}, _s} ->
        {:error, Mongo.Error.exception(tag: :tcp, action: "send", reason: reason)}
      {:disconnect, %{code: code, message: message}, _s} ->                                   #NEEDS TO BE ADDED                 
        {:error, Mongo.Error.exception(tag: :tcp, action: "recv", reason: message)}
      {:error, reason} ->
        {:error, reason}
    end
  end
```


In lib/mongo.ex we call the DBConnection.execute function numerous times.
When mongodb is not connected DBConnection.execute raises an error, which is not being caught, which causes the supervisor to crash.  This may be by design, but this is problematic as it is causing the entire app to crash when mongodb is disconnected.
This leaves us with two other possibilities that I can think of,
1. Adding a try/rescue block around DBConnection.execute (not very elixir like), but something similar to the code below would work.
```ruby
def direct_command(conn, query, opts \\ []) do
    params = [query]
    query = %Query{action: :command}
    try do
      with {:ok, reply} <- DBConnection.execute(conn, query, params,
                                                defaults(opts)) do
        case reply do
          op_reply(flags: flags, docs: [%{"$err" => reason, "code" => code}])
              when (@reply_query_failure &&& flags) != 0  ->
            {:error, Mongo.Error.exception(message: reason, code: code)}
          op_reply(flags: flags) when (@reply_cursor_not_found &&& flags) != 0 ->
            {:error, Mongo.Error.exception(message: "cursor not found")}
          op_reply(docs: [%{"ok" => 0.0, "errmsg" => reason} = error]) ->
            {:error, %Mongo.Error{message: "command failed: #{reason}", code: error["code"]}}
          # TODO: Check if needed
          op_reply(docs: []) ->
            {:ok, nil}
        end
      end
    rescue
      reason -> {:disconnect, Mongo.Error.exception(message: reason), "DBConnection error"}    
                  #Obviously we would want to parse the different reasons an error could be raised
    end
  end
```

2.  Checking that a connection to the database exits before calling  DBConnection.execute.

@michalmuskala would love your feedback on the best way to handle this.  I'll gladly fix it and make a pull request.

**Comment by ankhers** [comment]
This is unfortunately an issue that I am aware of.

I am unable to speak for the original author(s) for the replica set functionality. However, when I took it over, I thought it would be better to have the functionality in a mostly working state, than not have it at all.  As @michalmuskala pointed out in [this comment](https://github.com/ankhers/mongodb/pull/93#issuecomment-290746542), I will be going through the [`xandra`](https://github.com/lexhide/xandra) package to see how they are handling clustering while using the [`db_connection`](https://github.com/elixir-ecto/db_connection) package.

Unfortunately I do not currently have an ETA for when that work will be finished, but it is my current priority with this driver.
