### ISSUE TITLE
Checkout connection from pool for multiple operations

### ISSUE THREAD

**Issue by klmurphy72** [elixir-mongo/mongodb#230]
I believe that currently, when using a pool, a connection is checked out, the operation is performed and the connection is checked back in.

Is there a way to check out a connection, perform multiple operations with the connection, and then return the connection?

Thank you in advance.

**Comment by ankhers** [comment]
Currently, no. What is the usecase you have for this?

**Comment by klmurphy72** [comment]
I have an application that needs to update multiple collections when an event is received from an external source.  Having to check out and check in the connection for each update is quite time consuming.  I would like to get a connection, perform all of the operations, and then return it.  My other option is hundreds or possibly thousands of connections to the database.

My application is very database intensive as it polls external devices via TCP (Modbus) and then updates the database accordingly.  When using pools, the check-out/check-in becomes a bottleneck.

**Comment by klmurphy72** [comment]
Something like this will need to be implemented to support transactions with MongoDB 4.0, no?  A transaction is pointless unless it contains multiple operations.

**Comment by ankhers** [comment]
I have not looked into the details for transactions yet. So I cannot say with any certainty what will be needed. There has also been no work yet to support transactions. 

I believe you would be more interested in Mongo's Bulk Write feature. Though it is only for a single collection at a time. However, the person working on support for it has since stopped.
