### ISSUE TITLE
Mongo.Pool

### ISSUE THREAD

**Issue by ryanswapp** [elixir-mongo/mongodb#90]
I saw a previous issue that was the same as mine but the solution for them did not work for me (adding a name parameter to start_link). This is my first time using the library (version 2.0.0) and I followed the instructions in the README. I've got a MongoPool module:
```
defmodule MongoPool do
  use Mongo.Pool, name: __MODULE__, adapter: Mongo.Pool.Poolboy
end
```
and when the app tries to compile I get the following error:
```
** (CompileError) lib/intake_zen/mongo_pool.ex:2: module Mongo.Pool is not loaded and could not be found
    (elixir) expanding macro: Kernel.use/2
    lib/intake_zen/mongo_pool.ex:2: MongoPool (module)
    (elixir) lib/kernel/parallel_compiler.ex:116: anonymous fn/4 in Kernel.ParallelCompiler.spawn_compilers/1
```
I searched through the driver repo and can't find Mongo.Pool anywhere. Is this module no longer available?

**Comment by ericmj** [comment]
The readme is outdated. Do `Mongo.start_link(...)` instead.

**Comment by tomjoro** [comment]
See issue #88 for details on using with Phoenix.

**Comment by ryanswapp** [comment]
Sounds good. Thanks!

**Comment by jb41** [comment]
@ericmj @tomjoro @ryanswapp 
Can someone provide a solution how to make it work with Phoenix? I can create a PR for updating README to be up to date.

**Comment by tomjoro** [comment]
The current README does not have Phoenix instructions. However, I think it is a common use case so having some guidelines would help. Further confusing things is the Ecto MongoDB stuff which is not supported (and probably will never be for good reasons).  We use Phoenix + MongoDB driver + Ecto.Changeset  and it works great. 

MongoPool is gone. Instead you should use standard process mechanisms.

>      {:ok, pid} = Mongo.start_link(database: "mongodb_works", name: :mongo)


And then all queries can use either pid or the name you give it when you start the link.

> Mongo.insert_one(pid, "any", %{foo: 42})
> Mongo.insert_one(:mongo, "any", %{foo: 42})

When using in Phoenix, you just have to have worker start the named process like so (in the children [])

>       worker(Mongo, [[database: Application.get_env(:my_app, :db)[:name], name: :mongo]])


Note, that I use a environment configuration to specify the db name so I can have different dev, test, and prod databases.

Also I figured out how to do indexes, which is non-trivial:

>     Mongo.command(:mongo, %{createIndexes: "users", indexes: [ %{ key: %{ "phone_number": 1 }, name: "phone_number_idx", unique: true} ] })

**Comment by ericmj** [comment]
> The current README does not have Phoenix instructions.

I don't see why it should have Phoenix instructions. The database library you use is completely orthogonal to the web framework you use, for good reason.

> Further confusing things is the Ecto MongoDB stuff which is not supported (and probably will never be for good reasons).

There is an ecto adapter for mongodb, but it's not updated for ecto 2.0 yet. There are PRs that work on updating this, if you need ecto 2.0 with mongodb I would suggest to check in and see if you can help out on the PRs.

I am sorry that the readme is outdated regarding the pooling, I will try to get to it asap.

**Comment by tomjoro** [comment]
I agree totally (I accidentally posted my comment above before I got done with the details)... I'm just trying to help... People don't understand that a) Mongo drivers work fine with Phoenix, and b) You don't really need Ecto stuff with Mongo anyways, but you can still use Ecto things like Changesets.  Long story short, I think people are not using Mongo in Phoenix projects because of the lack of Ecto 2.0 support (which shouldn't be a barrier). Maybe some blog would help too. I can help with documentation, etc., 

Making Mongo adapter Ecto 2.0 compliant seems like a lot of work? (Not trying to downplay, but I don't see how they fit together). At the same time the support for replica sets, etc., are much anticipated updates to Mongo driver - great stuff that is needed in any production MongoDB installation. Also, having documentation for common things, like creating indexes, etc., is really helpful.

**Comment by ericmj** [comment]
I have updated the readme with proper pooling instructions now.

> Making Mongo adapter Ecto 2.0 compliant seems like a lot of work? (Not trying to downplay, but I don't see how they fit together).

It is a lot of work and there some incompatibilities but mongodb worked with Ecto 1.0 so I don't see why it shouldn't work with Ecto 2.0.

**Comment by tomjoro** [comment]
Thanks! 
Are you missing `database` in the worker configuration in README?

**Comment by tomjoro** [comment]
We used the Ecto 1.0 drivers for a while. We now use Ecto 2.0, but with MongoDB driver (no ecto mongo adapter). I think it actually works better..  Here's a typical thing we do:

>   {:ok, result} = Mongo.find_one_and_update(:mongo, "users",
>       %{"uuid" => user_uuid, "business_connections.id" => business_connection_id},
>       %{"$set" => %{ "business_connections.$.status" => "APPROVED"} }, [return_document: :after])

This is beautiful and can easily be understood (and preferred?) by anyone who has used MongoDB. 
There are many things that can be done with Mongodb that just don't have an equivalent in Ecto/relational dbs. So, making it 'work' with Ecto queries is possible, but can I use all the cool features of MongoDb then? 

It would be great to have a robust (it is robust already!) MongoDb driver, that supported Ecto.Changsets, Ecto.Schema, etc., but also supported replica-sets, ensure index, map/reduce, aggregation pipeline, deep nested array queries with updates (and indexes on them too)... Maybe an Ecto branch rather than Ecto adapter...?

And thanks again for all the hard work. The quality of this driver, and Ecto in general, is great.
